import postgres from "postgres";

/**
 * Slug-existence checks for the public content detail routes, used by
 * `src/proxy.ts` to return a real HTTP 404 instead of a soft 404.
 *
 * Deliberately standalone rather than reusing `@/drizzle`:
 *
 * - Proxy runs as its own bundle. Importing the Drizzle client would pull the
 *   entire schema barrel and `@t3-oss/env-nextjs` (which validates ~20 unrelated
 *   variables at import) into a module that runs on every content request.
 * - Next's proxy docs are explicit: "Keep proxy checks fast, and avoid fetching
 *   full content there."
 *
 * Each query mirrors the publication filter of the tRPC procedure that backs the
 * corresponding page. If these ever drift, the proxy will 404 a live page — the
 * `returns 200` guards in `e2e/seo.spec.ts` exist to catch exactly that.
 *
 * Physical column names are quoted camelCase: this schema is generated by
 * drizzle-kit with no `casing` option, so keys are used verbatim (`"deletedAt"`,
 * not `deleted_at`). See `src/drizzle/migrations/0000_amazing_charles_xavier.sql`.
 */

export const SLUG_KINDS = ["blog", "work", "services"] as const;
export type SlugKind = (typeof SLUG_KINDS)[number];

/**
 * Hang-guard, not a latency budget. It must be generous enough to absorb a cold
 * connection — a fresh proxy instance pays TCP + TLS + auth, and a suspended
 * Neon compute can take seconds to wake. A tight budget here does not make slow
 * requests fast; it just makes the first request to every cold instance fall
 * open and serve the soft 404 this module exists to remove.
 *
 * Waiting costs nothing real: the page performs the same lookup immediately
 * afterwards, so if this query is slow the request was going to be slow anyway.
 */
const QUERY_TIMEOUT_MS = 5_000;

/**
 * Cached so repeated requests reuse one connection, and so dev HMR does not leak
 * a new pool per reload. This is a resource handle, not state shared with the
 * app — the proxy still passes information onward only via the response.
 */
const globalForSlugDb = globalThis as unknown as {
  slugConn: postgres.Sql | undefined;
};

function getConnection(): postgres.Sql | null {
  const url = process.env.DATABASE_URL;
  if (!url) return null;

  if (!globalForSlugDb.slugConn) {
    globalForSlugDb.slugConn = postgres(url, {
      // Every request to a content detail route passes through here, so the
      // pool must not become a serialization point. `max: 1` measured 5.8s
      // under 20 concurrent requests; this keeps them flat while staying small
      // enough to sit alongside the application's own pool.
      max: 10,
      connect_timeout: 5,
      idle_timeout: 20,
    });
  }

  return globalForSlugDb.slugConn;
}

type FoundRow = { found: boolean };

function existsQuery(sql: postgres.Sql, kind: SlugKind, slug: string) {
  switch (kind) {
    case "blog":
      return sql<FoundRow[]>`
        select exists (
          select 1 from "blog_posts"
          where "slug" = ${slug}
            and "status" = 'published'
            and "deletedAt" is null
        ) as "found"
      `;
    case "work":
      return sql<FoundRow[]>`
        select exists (
          select 1 from "case_studies"
          where "slug" = ${slug}
            and "status" = 'published'
            and "deletedAt" is null
        ) as "found"
      `;
    case "services":
      return sql<FoundRow[]>`
        select exists (
          select 1 from "services"
          where "slug" = ${slug}
            and "isActive" = true
            and "deletedAt" is null
        ) as "found"
      `;
  }
}

/**
 * `true` — the slug is published and the page will render.
 * `false` — the slug is definitely absent; the caller should serve a 404.
 * `null` — undetermined (no database URL, timeout, or query error).
 *
 * `null` is the fail-open case and must never be treated as `false`: a false 404
 * on a live page is far worse than the soft 404 this module exists to remove.
 */
export async function isPublishedSlug(
  kind: SlugKind,
  slug: string,
): Promise<boolean | null> {
  const sql = getConnection();
  if (!sql) return null;

  let timer: ReturnType<typeof setTimeout> | undefined;

  try {
    const rows = await Promise.race([
      existsQuery(sql, kind, slug),
      new Promise<never>((_, reject) => {
        timer = setTimeout(
          () => reject(new Error("slug lookup timed out")),
          QUERY_TIMEOUT_MS,
        );
      }),
    ]);

    const found = rows[0]?.found;
    return typeof found === "boolean" ? found : null;
  } catch {
    // Fail open — render the page and accept a soft 404 rather than risk
    // 404ing live content because the database was briefly unreachable.
    return null;
  } finally {
    if (timer) clearTimeout(timer);
  }
}
